version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --filter "name=python-csv"
    networks:
      - myappnetwork
  python:
    build: ./python-csv
    container_name: python-csv
    ports:
      - 8000:8000
    environment:
      - AUTH_TOKEN=maxsimus
    networks:
      - myappnetwork
    depends_on:
      - db
      - alembic
    command: bash -c "sleep 4 && alembic upgrade head && gunicorn -b 0.0.0.0:8000 server:app && docker image prune -f"
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bridge-db
    ports:
      - "5858:5432"
    networks:
      - myappnetwork
    volumes:
      - ./data:/var/lib/postgresql/data

  alembic:
    build: ./python-csv
    container_name: alembic
    depends_on:
      - db
    networks:
      - myappnetwork
    command: bash -c "sleep 10 && alembic revision --autogenerate -m 'Initial migration' && alembic upgrade head"

networks:
  myappnetwork: