FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Build the Vue.js application
RUN npm run build

# Expose the port on which the Vue.js application will run (default is 8080)
EXPOSE 8080

# Specify the command to run the Vue.js application
CMD [ "npm", "run", "serve" ] 