"""Initial migration

Revision ID: 6b75d3d2e630
Revises: 9f8b0be80b0e
Create Date: 2023-06-27 18:49:26.580332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b75d3d2e630'
down_revision = '9f8b0be80b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maxsimus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max1', sa.Integer(), nullable=True),
    sa.Column('max2', sa.String(), nullable=True),
    sa.Column('max3', sa.String(), nullable=True),
    sa.Column('max4', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['max1'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maxsimus')
    # ### end Alembic commands ###
