"""Initial migration

Revision ID: 9f8b0be80b0e
Revises: 
Create Date: 2023-06-27 18:37:31.795947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8b0be80b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasetsId', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('dateOfBirth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('maritalStatus', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datasetsId'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basicData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('religionViews', sa.String(), nullable=True),
    sa.Column('politicalViews', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('mobilePhone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('linkedAccounts', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('sessionState', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('recentPages', sa.Text(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('productName', sa.String(), nullable=True),
    sa.Column('productPrice', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('subTotal', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('couponCode', sa.String(), nullable=True),
    sa.Column('shippingInformation', sa.Text(), nullable=True),
    sa.Column('taxInformation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('emails', sa.Text(), nullable=True),
    sa.Column('phones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviceInformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('operatingSystem', sa.String(), nullable=True),
    sa.Column('displayResolution', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('ISP', sa.String(), nullable=True),
    sa.Column('adBlock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalInterests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('briefDescription', sa.Text(), nullable=True),
    sa.Column('hobby', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placeOfResidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('currentCity', sa.String(), nullable=True),
    sa.Column('birthPlace', sa.String(), nullable=True),
    sa.Column('otherCities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('profileIds', sa.Text(), nullable=True),
    sa.Column('basicDataIds', sa.Text(), nullable=True),
    sa.Column('contactsIds', sa.Text(), nullable=True),
    sa.Column('workAndEducationIds', sa.Text(), nullable=True),
    sa.Column('placeOfResidenceIds', sa.Text(), nullable=True),
    sa.Column('personalInterestsIds', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workAndEducation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.Column('placeOfWork', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profileId'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workAndEducation')
    op.drop_table('settings')
    op.drop_table('placeOfResidence')
    op.drop_table('personalInterests')
    op.drop_table('deviceInformation')
    op.drop_table('credentials')
    op.drop_table('cookies')
    op.drop_table('contacts')
    op.drop_table('basicData')
    op.drop_table('profile')
    op.drop_table('datasets')
    # ### end Alembic commands ###
