"""Initial migration

Revision ID: c06ae472c719
Revises: 64f50929b27a
Create Date: 2023-06-29 17:29:48.887638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06ae472c719'
down_revision = '64f50929b27a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
































