# Используем базовый образ Python
FROM python:3.10.6

WORKDIR /python-vue
COPY . /python-vue

# Устанавливаем зависимости Python-приложения
RUN pip install -r requirements.txt

# Копируем исходный код в контейнер
EXPOSE 8000
# Запускаем приложение при старте контейнера
CMD ["python", "server.py"]
